In [1]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

In [35]:
gamified_bvp = pd.read_csv('./data/survey/gamified_bvp.csv').drop(columns=['Unnamed: 0'])
gamified_bvp

        subject    bvp  time_elapsed
0            11   0.29      0.000000
1            11   0.25      0.015625
2            11   0.18      0.031250
3            11   0.14      0.046875
4            11   0.15      0.062500
...         ...    ...           ...
160127       23  32.50    258.937500
160128       23  33.30    258.953125
160129       23  33.54    258.968750
160130       23  32.81    258.984375
160131       23  31.20    259.000000

[160132 rows x 3 columns]

In [36]:
non_gamified_bvp = pd.read_csv('./data/survey/non_gamified_bvp.csv').drop(columns=['Unnamed: 0'])
non_gamified_bvp

        subject    bvp  time_elapsed
0            13  64.00      0.000000
1            13  -0.00      0.015625
2            13  -0.00      0.031250
3            13  -0.00      0.046875
4            13  -0.00      0.062500
...         ...    ...           ...
211145       15  17.59    205.937500
211146       15  14.49    205.953125
211147       15  10.80    205.968750
211148       15   6.69    205.984375
211149       15   2.30    206.000000

[211150 rows x 3 columns]